### ISSUE TITLE
Docker nessus scanner status is working but not scanning the assets

### ISSUE THREAD

**Issue by prabha1331** [SteveMcGrath/docker-nessus_scanner#11]
Docker nessus scanner is connected to securitycenter and status is working but when i launch any scan, its unable to scan any asset even the host which has nessus docker container!!

**Comment by SteveMcGrath** [comment]
that sounds like a networking issue.  If SC can communicate to the scanner, then it should work.  I'd recommend looking at the docker networking configuration and go from there.

**Comment by prabha1331** [comment]
@SteveMcGrath Nessuss scanner is required port 8834 to communicate with SC, which I have binded docker Nessus's 8834 port with local host. After this SC is able to communicate with docker nessus. 
But is there any other network configuration required for containerized docker scanner to scan assets? Can you please elaborate more on your suggestion **looking at the docker networking configuration** because I don't have any specific docker network configuration set. Thanks.

**Comment by SteveMcGrath** [comment]
have you looked at the stdout of the scanner while you attempt to run a scan?
