### ISSUE TITLE
Scanner Groups

### ISSUE THREAD

**Issue by mbauer-mdc** [SteveMcGrath/docker-nessus_scanner#12]
Is there a way when deploying with docker to add a scanner to a scanner group? I do believe this would be ideal if not.

**Comment by SteveMcGrath** [comment]
there isnt any way using NessusCLI to do that today that I'm aware of.  This would require talking to the Tenable.io API directly.

**Comment by mbauer-mdc** [comment]
Got it. I had assumed that you could add it like the agent. I can figure out a work around on my end in deployment then.

**Comment by mbauer-mdc** [comment]
This can be closed.
