### ISSUE TITLE
container stopped when stop the Nessusd service

### ISSUE THREAD

**Issue by kmcyjm** [SteveMcGrath/docker-nessus_scanner#13]
when the Nessusd service is stopped, the container is stopped as well.
I sometimes need to stop the Nessusd service before rebuilding the Nessus database. However, when the service is stopped, the container is stopped as a result of it.
Is there a way to prevent this?

**Comment by mattlorimor** [comment]
Can you post the exact commands you are running that cause the container to exit?

My hunch is that you are killing the `/opt/nessus/sbin/nessus-service` process which, if stopped, kills the container since it is _the_ process keeping the container running.

![image](https://user-images.githubusercontent.com/1616060/79672115-c6e10500-8194-11ea-8283-6aaf4d1e709e.png)

**Comment by kmcyjm** [comment]
you are correct.

I used the init script from Ubuntu as follows which basically kills the process of nessusd service.

I am wondering if the nessusd service can run in the background (i tried to use -D flag with no luck) when we start the container, and make them independent of each other, so stopping the service won't impact the execution of the container?

```bash
NESSUS_PREFIX="/opt/nessus"
NESSUS_NAME="Nessus"
NESSUS_SERVICE=${NESSUS_PREFIX}/sbin/nessus-service
NESSUS_PID_FILE=${NESSUS_PREFIX}/var/nessus/nessus-service.pid

test -x $NESSUS_SERVICE || {
  echo "$NESSUS_NAME not properly installed"
  exit 1
}

RETVAL=0


start() {
  KIND="$NESSUS_NAME" 
  echo -n $"Starting $NESSUS_NAME : "
  $NESSUS_SERVICE -D -q
  echo "."
  return 0
}   

stop() {
  echo -n $"Shutting down $NESSUS_NAME : "
  if [ -f "$NESSUS_PID_FILE" ]
  then
    pid=$(cat $NESSUS_PID_FILE)
    if [ -n "$pid" -a -d /proc/$pid ]
    then
      kill $pid
    fi  
  fi  
  echo "."
  return 0
}  
```

**Comment by mattlorimor** [comment]
> I sometimes need to stop the Nessusd service before rebuilding the Nessus database.

Are you referring to rebuilding the plugin database? If so, `nessusd` provides a command to rebuild it:

```
/opt/nessus/sbin/nessusd -R
```

Unless I'm missing something, you should be able run that without the container being killed. I just tried doing so on a Nessus scanner that is attached to Tenable.sc (formerly SecurityCenter), and it shows a normal status in the scanners list in Tenable.sc after the rebuild.

> I am wondering if the nessusd service can run in the background (i tried to use -D flag with no luck) when we start the container, and make them independent of each other, so stopping the service won't impact the execution of the container?

@SteveMcGrath would have to speak to this.

**Comment by kmcyjm** [comment]
I am doing both -t and -R.
As per the official kb, it is recommended to stop the service before rebuilding the db. I guess the db may prone to be corrupted otherwise.
https://community.tenable.com/s/article/Rebuild-the-Plugin-Database

**Comment by kmcyjm** [comment]
`/opt/nessus/sbin/nessusd -R` would not cause the container being stopped, it is the nessusd service.

**Comment by kmcyjm** [comment]
> > I sometimes need to stop the Nessusd service before rebuilding the Nessus database.
> 
> Are you referring to rebuilding the plugin database? If so, `nessusd` provides a command to rebuild it:
> 
> ```
> /opt/nessus/sbin/nessusd -R
> ```
> 
> Unless I'm missing something, you should be able run that without the container being killed. I just tried doing so on a Nessus scanner that is attached to Tenable.sc (formerly SecurityCenter), and it shows a normal status in the scanners list in Tenable.sc after the rebuild.
> 
> > I am wondering if the nessusd service can run in the background (i tried to use -D flag with no luck) when we start the container, and make them independent of each other, so stopping the service won't impact the execution of the container?
> 
> @SteveMcGrath would have to speak to this.

**Comment by kmcyjm** [comment]
Mistakenly closed this issue, re-open it.

**Comment by mattlorimor** [comment]
Yeah, following the official KB is completely fair and reasonable. I'm not exactly sure what the best advice is in this scenario.

I'd wait for @SteveMcGrath to pop by.

**Comment by SteveMcGrath** [comment]
I had already checked out for the day when you guys decided to start working through this ;)

As for the container you're running, Are you running the /opt/nessus/var/nessus in a volume or no?  If you are, you could always simply shut down the container, spin up a new one with that volume mounted and overload the command to be nessusd -R.

While its not something I have personally tested, there is no reason why it shouldn't work.

**Comment by SteveMcGrath** [comment]
@kmcyjm @mattlorimor anything further on this one, or am I ok-to-close?

**Comment by kmcyjm** [comment]
@SteveMcGrath thanks for the follow-up.
Did some tests however encountered some other issues.
You can close this issue now. Will open a new one if any further assistance is needed.
Thanks a mil!

**Comment by SteveMcGrath** [comment]
If the other issues relate to the image, please open up other issues, even if you have a solution.  The only way the image can be improved is to have these highlighted, documented, and worked out.

Thanks!
