### ISSUE TITLE
PDF Reporting does not work

### ISSUE THREAD

**Issue by fancyHeat** [SteveMcGrath/docker-nessus_scanner#14]
I believe that Java must be installed.

**Comment by SteveMcGrath** [comment]
latest, 8, 8.10, and 8.10.0 now have Java 11 OpenJDK headless installed.

**Comment by fancyHeat** [comment]
Okay.. PDF reporting still doesn't work

**Comment by SteveMcGrath** [comment]
I just ran a successful PDF export from a scanner using this image.  Can you confirm that you are on the latest image? (hash ae9bdd214c89)

**Comment by fancyHeat** [comment]
It works now.. image was stale. Fantastic work
