### ISSUE TITLE
Can't read cakey.pem

### ISSUE THREAD

**Issue by eng3** [SteveMcGrath/docker-nessus_scanner#16]
I was able to install, setup and run.  After an update of the image, the web interface no longer loads.  I tried deleting and repulling but that does not fix the issue.  

nessusd.dump says it cannot read cakey.pem

```
[Tue Jul  7 20:01:56 2020][8.1][op=_qdb_map_lowmem][name=plugins-code.db.15941658001239337441][fd=7][map_sz=0][file_size=2763298225]: complete
[Tue Jul  7 20:02:16 2020][7.1] /opt/nessus/var/nessus/CA/cakey.pem: Operation not permitted
[Tue Jul  7 20:02:16 2020][7.1] /opt/nessus/com/nessus/CA/cacert.pem: No such file or directory
[Tue Jul  7 20:02:19 2020][7.1][op=_qdb_map][name=services-udp.db][fd=-1][map_sz=38575]: complete
[Tue Jul  7 20:02:19 2020][7.1][op=_qdb_map][name=services-tcp.db][fd=-1][map_sz=40899]: complete
[Tue Jul  7 20:02:20 2020][7.1][op=_qdb_map][name=services-tcp.db][fd=-1][map_sz=40899]: complete
[Tue Jul  7 20:02:20 2020][7.1][op=qdb_sync][name=upgrades.db][fd=5][map_sz=0][file_size=55]: complete
[Tue Jul  7 20:02:27 2020][7.21][sched=100][pid=51][plugin=nessusd_www_server6.nbin][instr=0xcf70] : SSL_CTX_use_certificate_file() failed
call stack:
-----------
[0cf70:Socket.accept+27] call, addr(0xf0000204), -, # ssl_accept4() [C func]
[0793d:Mug::Connection.on_client+46] refcall, fp(2), string#690, # from: fp(2)
[215e2:!anon5+4] refcall, fp(-2), string#4795, # from: fp(-2)
[2da2d:main+13281] eop, -, -,

```

However, if I attach to the shell, I can cat the file with no error.

Note, I have /opt/nessus/var/nessus in a separate volume for persistence.
Repulling without the volume works

**Comment by eng3** [comment]
I find that if I delete the contents of /opt/nessus/var/nessus/CA and restart the container, then it loads fine, though I must reactivate.  However, after each nightly update, the issue occurs again and I must repeat the process.

**Comment by SteveMcGrath** [comment]
I have seen a lot of issues with volumes and Nessus crop up recently.  Its why all of the images were reworked to not use anonymous volumes towards the beginning of the year.

I'm not sure what the root cause is here, however its a Nessus-specific issue.

**Comment by SteveMcGrath** [comment]
Volumes were removed
