### ISSUE TITLE
Adding MIT license

### ISSUE THREAD

**Issue by SteveMcGrath** [SteveMcGrath/docker-nessus_scanner#20]
As previous contributors I'd like to ask your permission to add the MIT license to this repository.
@eerichmond @wschoot @mattlorimor @lfaoro

**Comment by mattlorimor** [comment]
+1 lgtm

:shipit:

**Comment by wschoot** [comment]
Sure!

**Comment by SteveMcGrath** [comment]
I think @eerichmond is the only one of you not to respond yet.  Here are the commits he has submitted:

https://github.com/SteveMcGrath/docker-nessus_scanner/commits?author=eerichmond

Also thanks for the PR @lfaoro, making my life easy ;)

**Comment by lfaoro** [comment]
anytime Steve ;)

**Comment by lfaoro** [comment]
Eric hasn't pushed any code since Feb9, maybe he's on vacation -- unless you need unanimity for this, I believe the majority vote should be enough to settle the case :)
