### ISSUE TITLE
Scans not finishing (hang at 99%)

### ISSUE THREAD

**Issue by wschoot** [SteveMcGrath/docker-nessus_scanner#7]
This is not really an "issue", but more like a headsup in case you experience the same as we have.

We've been using your setup as boilerplate example for own images and I liked the redirection to /dev/stdout and / /dev/stderr a lot as this is the "Docker way" of doing logging. However, we've experienced many basic scans to "hang" at 99% and been debugging this downto these symlinks. I'm not really sure how or why (perhaps container-level filelocking?) but removing these symlinks (and have them log to the containers' storage) made the basic scans fly again.

Not sure if you've run into this as well or not, but if you do, see this as a possible pointer into solving this.

**Comment by SteveMcGrath** [comment]
Sorry for the delay on this one.  If this is happening, then it's definitely an issue.  Mind testing JUST removing the symlink to the `/opt/nessus/var/nessus/logs/nessusd.dump` and see if that solves the issue?

**Comment by SteveMcGrath** [comment]
For the time being, there is a temporary env var thats checked called NO_SYMLINK.  If that var is set to anything, then it will remove the symlinks at setup.  I'd like to continue to triage this however and figure out if it's a particular link that causes the hang.

**Comment by askldjd** [comment]
I got into the same issue where scans were stuck and would never complete. As @SteveMcGrath said, by deleting all the symlinks in `/opt/nessus/var/nessus/logs/` resolved the issue.

**Comment by SteveMcGrath** [comment]
so after some work with @askldjd, we were able to narrow down the issue to the nessusd.dump file.  It's no longer being redirected to stderr.  The rest of the links still exist as they don't seem to be impacting the scanner's ability to work and they behave as expected.

Please confirm that you're no longer seeing the issue @wschoot and I will close the issue.

**Comment by wschoot** [comment]
Works for me, go ahead and close the issue
