### ISSUE TITLE
NNM in a docker container

### ISSUE THREAD

**Issue by cmorgret** [SteveMcGrath/docker-nessus_scanner#8]
I am trying to run NNM in a docker container along side Security Onion so I that I can perform passive vulnerability scanning along side Security Onion NSM services. I am having trouble getting the image loaded and running so I can connect to NNM and set it up.

**Comment by SteveMcGrath** [comment]
This is in the wrong Repository.  Please refer to: https://github.com/SteveMcGrath/docker-nessus_monitor
